/**
 * AUTO-GENERATED. Do not edit by hand.
 *
 * Source: services/agents-api/openapi.json (committed)
 * Regenerate with: pnpm --filter @extratoast/agents-ui contract:generate
 * Drift gate: pnpm --filter @extratoast/agents-ui contract:check
 * Contract docs: services/agents-api/CONTRACT.md
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/staged-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stageInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/git/open-pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openPr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/links/{linkId}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachKey_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["linkRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["addLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByUser"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["send_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["appendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workspace runner setup metadata */
        get: operations["workspaceSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/setup-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List setup transition history for a workspace */
        get: operations["workspaceTransitionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["turns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current, pending, and failed setup state for a session */
        get: operations["sessionSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/setup-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List setup transition history for a session */
        get: operations["sessionTransitionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/setup-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview setup diff and validation for a session restart target */
        get: operations["setupPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}/setup-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List setup targets for a session with validation preview */
        get: operations["sessionSetupOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/links/{linkId}/setup-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["guide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["archive"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete: operations["archive_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-setups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List selectable agent setup catalog entries */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-setups/{setupId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an agent setup catalog entry */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["stop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/repositories/{repoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detachRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/links/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/repositories/{repoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unlinkRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkspaceRequest: {
            name: string;
            repoUrl?: string | null;
            branch?: string | null;
            /** @enum {string} */
            kind: "REPO_BACKED" | "SCRATCH" | "CHAT";
            /** Format: uuid */
            projectId?: string | null;
            /** Format: uuid */
            repositoryId?: string | null;
            /** Format: uuid */
            primaryRepositoryId?: string | null;
            repositoryIds?: string[] | null;
            /**
             * Format: uuid
             * @deprecated
             * @description Use repositoryId
             */
            githubLinkId?: string | null;
        };
        AgentSetupReferenceResponse: {
            id: string;
            /** Format: int64 */
            version: number;
        };
        WorkspaceResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            repoUrl?: string | null;
            branch?: string | null;
            podName?: string | null;
            gatewayEndpoint?: string | null;
            status: string;
            kind: string;
            /** Format: uuid */
            projectId?: string | null;
            /** Format: uuid */
            repositoryId?: string | null;
            /** Format: uuid */
            githubLinkId?: string | null;
            runnerSetup: components["schemas"]["WorkspaceRunnerSetupResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceRunnerSetupResponse: {
            current: components["schemas"]["AgentSetupReferenceResponse"];
            pending?: components["schemas"]["AgentSetupReferenceResponse"] | null;
            /** Format: int64 */
            generation: number;
            operation: string;
            /** Format: date-time */
            operationStartedAt?: string | null;
            /** Format: date-time */
            operationUpdatedAt?: string | null;
        };
        StartAgentSessionRequest: {
            /** @enum {string} */
            kind: "CLAUDE" | "CODEX" | "SHELL";
        };
        StageInputRequest: {
            content: string;
            name?: string | null;
        };
        StagedInputResponse: {
            path: string;
            /** Format: int64 */
            bytes: number;
            name: string;
        };
        RestartAgentSessionHttpRequest: {
            /** Format: int64 */
            expectedGeneration?: number | null;
            /** Format: int64 */
            expectedEpoch?: number | null;
            expectedSetupId?: string | null;
            /** Format: int64 */
            expectedSetupVersion?: number | null;
            expectedCurrentSetupId?: string | null;
            /** Format: int64 */
            expectedCurrentSetupVersion?: number | null;
            targetSetupId?: string | null;
            /** Format: int64 */
            targetSetupVersion?: number | null;
        };
        RestartAgentSessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: int64 */
            epoch: number;
            /** Format: int64 */
            generation: number;
            status: string;
            currentSetup: components["schemas"]["AgentSetupReferenceResponse"];
            pendingSetup?: components["schemas"]["AgentSetupReferenceResponse"] | null;
        };
        FieldError: {
            field: string;
            message: string;
            rejectedValue?: null;
        };
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string | null;
            /** Format: uri */
            instance?: string | null;
            errors: components["schemas"]["FieldError"][];
            traceId?: string | null;
            exception?: string | null;
            /** Format: int32 */
            kubernetesCode?: number | null;
            kubernetesReason?: string | null;
            constraint?: string | null;
            column?: string | null;
            referencedTable?: string | null;
            runnerStatus?: string | null;
            /** Format: int32 */
            retryAfterSeconds?: number | null;
        };
        SendUserInputRequest: {
            text: string;
            enter: boolean;
        };
        OpenPrRequest: {
            repoDir: string;
            title: string;
            body: string;
            base: string;
        };
        AttachWorkspaceRepositoryRequest: {
            /** Format: uuid */
            repositoryId: string | null;
        };
        WorkspaceConnectResponse: {
            /** Format: uuid */
            workspaceId: string;
            setupId: string;
            /** Format: int64 */
            setupVersion: number;
            state: string;
            reason?: string | null;
            /** Format: date-time */
            checkedAt: string;
        };
        CreateRepositoryRequest: {
            name: string;
            repoUrl: string;
            defaultBranch: string;
        };
        AccessVerificationResponse: {
            read?: boolean | null;
            write?: boolean | null;
            defaultBranchProtected?: boolean | null;
            /** Format: date-time */
            checkedAt?: string | null;
            messages: string[];
        };
        RepositoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            repoUrl: string;
            defaultBranch: string;
            vaultKeyPath: string;
            deployKeyFingerprint?: string | null;
            /** Format: date-time */
            deployKeyAddedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            verification?: components["schemas"]["AccessVerificationResponse"] | null;
        };
        AttachRepositoryDeployKeyRequest: {
            privateKeyOpenssh: string;
            publicKeyOpenssh: string;
            knownHosts?: string | null;
        };
        CreateProjectRequest: {
            name: string;
            slug: string;
            description?: string | null;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AttachDeployKeyRequest: {
            privateKeyOpenssh: string;
            publicKeyOpenssh: string;
            knownHosts?: string | null;
        };
        LinkRepositoryRequest: {
            /** Format: uuid */
            repositoryId: string;
        };
        AddGithubLinkRequest: {
            name: string;
            repoUrl: string;
            defaultBranch: string;
        };
        GithubLinkResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            repoUrl: string;
            defaultBranch: string;
            vaultKeyPath: string;
            deployKeyFingerprint?: string | null;
            /** Format: date-time */
            deployKeyAddedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateConversationRequest: {
            title: string;
        };
        ConversationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            title: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SendMessageRequest: {
            content: string;
        };
        MessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            role: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        StartChatSessionRequest: {
            title?: string | null;
            /** @enum {string|null} */
            kind?: "PLAIN" | "KNOWLEDGE" | null;
        };
        ChatSessionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            title?: string | null;
            status: string;
            kind: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AppendChatMessageRequest: {
            body: string;
            /** @enum {string} */
            role: "USER" | "ASSISTANT" | "SYSTEM";
        };
        ChatMessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            role: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        SetupTransitionHistoryResponse: {
            events: components["schemas"]["SetupTransitionResponse"][];
        };
        SetupTransitionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            sessionId?: string | null;
            from?: components["schemas"]["AgentSetupReferenceResponse"] | null;
            to: components["schemas"]["AgentSetupReferenceResponse"];
            /** @enum {string} */
            status: "REQUESTED" | "STARTED" | "COMPLETED" | "FAILED" | "CANCELLED";
            reason?: string | null;
            message?: string | null;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        TurnResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            role: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        FailedSessionSetupResponse: {
            setup: components["schemas"]["AgentSetupReferenceResponse"];
            reason?: string | null;
            message?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
        };
        SessionSetupStateResponse: {
            current: components["schemas"]["AgentSetupReferenceResponse"];
            pending?: components["schemas"]["AgentSetupReferenceResponse"] | null;
            failed?: components["schemas"]["FailedSessionSetupResponse"] | null;
        };
        AgentSetupBindingResponse: {
            kind: string;
            namespace: string;
            name: string;
            key?: string | null;
        };
        AgentSetupDiffChangeResponse: {
            field: string;
            fromValue?: string | null;
            toValue?: string | null;
            redacted: boolean;
        };
        AgentSetupDiffResponse: {
            from: components["schemas"]["AgentSetupReferenceResponse"];
            to: components["schemas"]["AgentSetupReferenceResponse"];
            hasChanges: boolean;
            changes: components["schemas"]["AgentSetupDiffChangeResponse"][];
        };
        AgentSetupValidationIssueResponse: {
            code: string;
            message: string;
            binding?: components["schemas"]["AgentSetupBindingResponse"] | null;
        };
        AgentSetupValidationResponse: {
            target: components["schemas"]["AgentSetupReferenceResponse"];
            valid: boolean;
            issues: components["schemas"]["AgentSetupValidationIssueResponse"][];
            warnings: components["schemas"]["AgentSetupValidationIssueResponse"][];
        };
        SetupPreviewResponse: {
            current: components["schemas"]["AgentSetupReferenceResponse"];
            target: components["schemas"]["AgentSetupReferenceResponse"];
            diff?: components["schemas"]["AgentSetupDiffResponse"] | null;
            validation: components["schemas"]["AgentSetupValidationResponse"];
        };
        AgentSetupCatalogEntryResponse: {
            setup: components["schemas"]["AgentSetupReferenceResponse"];
            displayName: string;
            description?: string | null;
            image: string;
            cliTools: {
                [key: string]: string;
            };
            toolProfiles: string[];
            toolAllowlist: string[];
            selectable: boolean;
            defaultSelectable: boolean;
            unavailableReason?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        SetupTargetOptionResponse: {
            setup: components["schemas"]["AgentSetupCatalogEntryResponse"];
            validation: components["schemas"]["AgentSetupValidationResponse"];
        };
        SetupTargetOptionsResponse: {
            current: components["schemas"]["AgentSetupReferenceResponse"];
            pending?: components["schemas"]["AgentSetupReferenceResponse"] | null;
            options: components["schemas"]["SetupTargetOptionResponse"][];
        };
        WorkspaceAgentSessionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** @enum {string} */
            kind: "CLAUDE" | "CODEX" | "SHELL";
            gatewayAgentId?: string | null;
            /** Format: int64 */
            epoch: number;
            /** Format: int64 */
            generation: number;
            /** Format: date-time */
            gatewayBoundAt?: string | null;
            status: string;
            idle: boolean;
            currentSetup: components["schemas"]["AgentSetupReferenceResponse"];
            pendingSetup?: components["schemas"]["AgentSetupReferenceResponse"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceDetailResponse: {
            workspace: components["schemas"]["WorkspaceWithRepositoriesResponse"];
            sessions: components["schemas"]["WorkspaceAgentSessionResponse"][];
        };
        WorkspaceRepositoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isPrimary: boolean;
            /** Format: date-time */
            attachedAt: string;
            repoUrl: string;
            defaultBranch: string;
            vaultKeyPath: string;
            deployKeyFingerprint?: string | null;
            /** Format: date-time */
            deployKeyAddedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            verification?: components["schemas"]["AccessVerificationResponse"] | null;
        };
        WorkspaceWithRepositoriesResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            repoUrl?: string | null;
            branch?: string | null;
            podName?: string | null;
            gatewayEndpoint?: string | null;
            status: string;
            kind: string;
            /** Format: uuid */
            projectId?: string | null;
            /** Format: uuid */
            repositoryId?: string | null;
            /** Format: uuid */
            githubLinkId?: string | null;
            repositories: components["schemas"]["WorkspaceRepositoryResponse"][];
            runnerSetup: components["schemas"]["WorkspaceRunnerSetupResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentSetupCatalogResponse: {
            setups: components["schemas"]["AgentSetupCatalogEntryResponse"][];
        };
        AgentSetupDetailResponse: {
            setup: components["schemas"]["AgentSetupReferenceResponse"];
            displayName: string;
            description?: string | null;
            namespace: string;
            image: string;
            imagePullPolicy: string;
            serviceAccount: string;
            /** Format: int32 */
            gatewayPort: number;
            claudeCredentialsPvc: string;
            codexCredentialsPvc: string;
            githubDeployKeySecret: string;
            cliTools: {
                [key: string]: string;
            };
            knowledgeBaseUrl: string;
            knowledgeBearerSecret: string;
            knowledgeBearerSecretKey: string;
            mcpServersConfigMap: string;
            defaultMcpProfile: string;
            connectorConfig: {
                [key: string]: string;
            };
            toolProfiles: string[];
            toolAllowlist: string[];
            dockerSocketEnabled: boolean;
            dockerSocketPath: string;
            dockerSocketSupplementalGroups: number[];
            nodeSelector: {
                [key: string]: string;
            };
            selectable: boolean;
            defaultSelectable: boolean;
            unavailableReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAgentSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    stageInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageInputRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StagedInputResponse"];
                };
            };
        };
    };
    restart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RestartAgentSessionHttpRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestartAgentSessionResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestartAgentSessionResponse"];
                };
            };
            /** @description Invalid setup request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendUserInputRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openPr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenPrRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attachRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachWorkspaceRepositoryRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runner is already ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceConnectResponse"];
                };
            };
            /** @description Runner boot in progress or just provisioned */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceConnectResponse"];
                };
            };
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceConnectResponse"];
                };
            };
            /** @description Runner unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceConnectResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryResponse"];
                };
            };
        };
    };
    attachKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachRepositoryDeployKeyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    attachKey_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                linkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachDeployKeyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    linkRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRepositoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    addLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGithubLinkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubLinkResponse"];
                };
            };
        };
    };
    listByUser: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"][];
                };
            };
        };
    };
    send_1: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatSessionResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartChatSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatSessionResponse"];
                };
            };
        };
    };
    appendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendChatMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatMessageResponse"];
                };
            };
        };
    };
    workspaceSetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceRunnerSetupResponse"];
                };
            };
        };
    };
    workspaceTransitionHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetupTransitionHistoryResponse"];
                };
            };
        };
    };
    turns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnResponse"][];
                };
            };
        };
    };
    sessionSetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionSetupStateResponse"];
                };
            };
        };
    };
    sessionTransitionHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetupTransitionHistoryResponse"];
                };
            };
        };
    };
    setupPreview: {
        parameters: {
            query: {
                targetSetupId: string;
                targetSetupVersion: number;
            };
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetupPreviewResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    sessionSetupOptions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetupTargetOptionsResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceDetailResponse"];
                };
            };
        };
    };
    destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                linkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "text/plain": string;
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    archive_1: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentSetupCatalogResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setupId: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentSetupDetailResponse"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detachRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                repoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                linkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unlinkRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                repoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
